POST http://localhost:4000/app/signup 
Content-Type: application/json

{
    "firstName":"Jhonny",
    "lastName":"Boy",
    "email":"boyjohn@gmail.com",
    "companyName":"",
    "password":"jhonnyBoy123"
}